// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPjjqlpM9bCz6zANSTpiOsNWAV6fCW_5o',
    appId: '1:193322388789:web:d9d0a90a505a3b84eed07c',
    messagingSenderId: '193322388789',
    projectId: 'livescoreapp-assignment',
    authDomain: 'livescoreapp-assignment.firebaseapp.com',
    storageBucket: 'livescoreapp-assignment.appspot.com',
    measurementId: 'G-4Z0DVKQL62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkQxnujRDt9tJxX1I1WH7LnhAP6SZxULs',
    appId: '1:193322388789:android:51f6707ec7137232eed07c',
    messagingSenderId: '193322388789',
    projectId: 'livescoreapp-assignment',
    storageBucket: 'livescoreapp-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0PKnhdo3gbPxexwYPoOKhQmsUH4HSHv8',
    appId: '1:193322388789:ios:8102bb194486aff7eed07c',
    messagingSenderId: '193322388789',
    projectId: 'livescoreapp-assignment',
    storageBucket: 'livescoreapp-assignment.appspot.com',
    iosBundleId: 'com.example.livescoreappAssignment',
  );
}
